---
title: "NARA_S_Output"
author: "Toon Van Daele"
date: "28 februari 2018"
output: html_document
params:
  modelname: "none"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
modelname <- params$modelname #"allsp"
path <- paste0("../data/data-out/", modelname, "/")
```

Generating output for NARA_S of model: **`r modelname`**

```{r loaddata}
df_probs <- readRDS(file = paste0(path, "df_probs.RDS"))
df_meval <- readRDS(file = paste0(path, "df_meval.RDS"))
df_redlist <- readRDS(file = paste0(path, "df_redlist.RDS"))
```

All species and all models

```{r all_species}
df_sums <- df_probs %>%
  dplyr::group_by(utmID, projname) %>%
  dplyr::summarise(probsum = sum(probs) / 1000) %>%
  spread(key = projname, value = probsum) %>%
  mutate_at(vars(contains("kr")),
                  .funs = funs(v = . - get(paste0(modelname, "_Current"))))

saveRDS(df_sums, file = paste0(path, "df_sums.RDS"))
write.table(df_sums, file = paste0(path, "df_sums.csv"),
            quote = FALSE, sep = ";", dec = ",", row.names = FALSE)
remove(df_sums)
```

Model selection: Select only species with ensemble AUC >= 0.7

```{r selection auc}
sp_sel <- df_meval %>%
  filter(Eval.metric == "ROC") %>%
  group_by(sp_n) %>%
  summarise(medianROC = mean(median)) %>%
  filter(medianROC >= 0.7) %>%
  pull(sp_n)

df_sums_auc <- df_probs %>%
  filter(sp_n %in% sp_sel) %>%
  dplyr::group_by(utmID, projname) %>%
  dplyr::summarise(probsum = sum(probs) / 1000) %>%
  spread(key = projname, value = probsum) %>%
  mutate_at(vars(contains("kr")),
                  .funs = funs(v = . - get(paste0(modelname, "_Current"))))

saveRDS(df_sums_auc, file = paste0(path, "df_sums_auc.RDS"))
write.table(df_sums_auc, file = paste0(path, "df_sums_auc.csv"),
            quote = FALSE, sep = ";", dec = ",", row.names = FALSE)
remove(df_sums_auc)
```

